<?php

namespace ContainerJ87TgqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payum' shared service.
     *
     * @return \Payum\Core\Payum
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['payum'] = $container->createProxy('PayumProxyC7d930b', static fn () => \PayumProxyC7d930b::createLazyProxy(static fn () => self::do($container, false)));
        }

        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/GatewayRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/GatewayFactoryRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/StorageRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Registry/RegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Payum.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/PayumBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/HttpRequestVerifierBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/TokenFactoryBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/CoreGatewayFactoryBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/GatewayFactoryBuilder.php';

        $a = new \Payum\Core\PayumBuilder();

        $b = new \Payum\Core\Bridge\Symfony\Builder\CoreGatewayFactoryBuilder();
        $b->setContainer($container);

        $a->setMainRegistry(($container->services['payum.static_registry'] ?? $container->load('getPayum_StaticRegistryService')));
        $a->setHttpRequestVerifier(new \Payum\Core\Bridge\Symfony\Builder\HttpRequestVerifierBuilder());
        $a->setTokenFactory(new \Payum\Core\Bridge\Symfony\Builder\TokenFactoryBuilder(($container->services['router'] ?? self::getRouterService($container))));
        $a->setTokenStorage(($container->services['payum.security.token_storage'] ?? $container->load('getPayum_Security_TokenStorageService')));
        $a->setGenericTokenFactoryPaths(['capture' => 'payum_capture_do', 'notify' => 'payum_notify_do', 'authorize' => 'payum_authorize_do', 'refund' => 'payum_refund_do', 'cancel' => 'payum_cancel_do', 'payout' => 'payum_payout_do']);
        $a->setCoreGatewayFactory($b);
        $a->addCoreGatewayFactoryConfig(['payum.template.layout' => '@PayumCore\\layout.html.twig', 'payum.template.obtain_credit_card' => '@PayumSymfonyBridge\\obtainCreditCard.html.twig', 'payum.paths' => ['PayumSymfonyBridge' => (\dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Resources/views')], 'payum.action.get_http_request' => ($container->services['payum.action.get_http_request'] ?? $container->load('getPayum_Action_GetHttpRequestService')), 'payum.action.obtain_credit_card' => ($container->services['payum.action.obtain_credit_card_builder'] ?? $container->load('getPayum_Action_ObtainCreditCardBuilderService'))]);
        $a->addGateway('offline', ['factory' => 'offline']);
        $a->setGatewayConfigStorage(($container->services['payum.dynamic_gateways.config_storage'] ?? $container->load('getPayum_DynamicGateways_ConfigStorageService')));
        $a->addCoreGatewayFactoryConfig(['twig.env' => ($container->services['twig'] ?? self::getTwigService($container))]);
        $a->addCoreGatewayFactoryConfig(['payum.action.sylius.authorize_payment' => '@sylius.payum_action.authorize_payment', 'payum.action.sylius.capture_payment' => '@sylius.payum_action.capture_payment', 'payum.action.sylius.payum_action.execute_same_request_with_payment_details' => '@sylius.payum_action.execute_same_request_with_payment_details', 'payum.action.sylius.resolve_next_route' => '@sylius.payum_action.resolve_next_route', 'payum.extension.psr_logger' => '@payum.extension.logger', 'payum.extension.log_executed_actions' => '@payum.extension.log_executed_actions', 'payum.extension.profile_collector' => '@payum.profiler.payum_collector', 'payum.prepend_extensions' => ['payum.extension.profile_collector', 'payum.extension.sylius.payum_extension.update_payment_state'], 'payum.extension.payum.extension.storage.app_entity_order_order' => '@payum.extension.storage.app_entity_order_order', 'payum.extension.payum.extension.storage.app_entity_payment_payment' => '@payum.extension.storage.app_entity_payment_payment', 'payum.extension.sylius.payum_extension.update_payment_state' => '@sylius.payum_extension.update_payment_state']);
        $a->addGatewayFactoryConfig('paypal_express_checkout', ['payum.action.sylius.paypal_express_checkout.convert_payment' => '@sylius.payum_action.paypal_express_checkout.convert_payment']);
        $a->addGatewayFactoryConfig('offline', ['payum.action.sylius.offline.convert_payment' => '@sylius.payum_action.offline.convert_payment', 'payum.action.sylius.offline.status' => '@sylius.payum_action.offline.status', 'payum.action.sylius.offline.resolve_next_route' => '@sylius.payum_action.offline.resolve_next_route']);
        $a->addGatewayFactoryConfig('sylius.pay_pal', ['payum.action.payum.action.authorize' => '@Sylius\\PayPalPlugin\\Payum\\Action\\AuthorizeAction', 'payum.action.payum.action.capture' => '@Sylius\\PayPalPlugin\\Payum\\Action\\CaptureAction', 'payum.action.payum.action.complete_order' => '@Sylius\\PayPalPlugin\\Payum\\Action\\CompleteOrderAction', 'payum.action.sylius.resolve_next_route' => '@Sylius\\PayPalPlugin\\Payum\\Action\\ResolveNextRouteAction']);
        $a->addGatewayFactory('sylius.pay_pal', new \Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder('Sylius\\PayPalPlugin\\Payum\\Factory\\PayPalGatewayFactory'));

        return $a->getPayum();
    }
}
