<?php

namespace Container0SxZZDh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Security_RequestMatcher_WtEFXHZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.security.request_matcher.WtEFXHZ' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\ChainRequestMatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.security.request_matcher.WtEFXHZ'] = new \Symfony\Component\HttpFoundation\ChainRequestMatcher([($container->privates['.security.request_matcher.3CutM45'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\PathRequestMatcher('^/'.$container->getEnv('string:resolve:SYLIUS_ADMIN_ROUTING_PATH_NAME')))]);
    }
}
